spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/product
    username: njidda
    password: njidda
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 1
    user: njidda
    password: njidda
server:
  port: 8050
